.\" Copyright (c) 2020, Rachel Michaela Bradley
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" 1. Redistributions of source code must retain the above copyright notice, 
.\"   this list of conditions and the following disclaimer.
.\"
.\" 2. Redistributions in binary form must reproduce the above copyright notice,
.\"    this list of conditions and the following disclaimer in the documentation
.\"    and/or other materials provided with the distribution.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.Dd December 23, 2020
.Dt AUTOEXEC 8
.Os
.Sh NAME
.Nm autoexec
.Nd automated iocage-managed jail command execution
.Sh SYNOPSIS
.Nm
.Op Ar """command""
.Sh DESCRIPTION
The autoexec utility uses iocage exec to automate command execution in every
jail managed by the iocage(8) utility.
.Pp
The autoexec utility requires the following argument:
.Bl -tag -width indent
.It Sy """command""
The command that should be executed in every jail.
.El
.Pp
The following options are available:
.Bl -tag -width indent
.It Sy -f
Passes the -f flag with exec, starting jails that are currently stopped.
.Sh EXAMPLES
To run "pkg upgrade -y" in every jail that is not stopped, use the following
command.
.Dl $ autoexec """pkg upgrade -y""
.Pp
.Sh FILES
/usr/local/bin/autoexec
.Sh SEE ALSO
.Xr iocage 8
.Sh AUTHORS
.An Rachel Michaela Bradley
.Aq contact@delevingne.me